<<<<<<< HEAD
export { Client as EscrowClient } from "./generated/escrow-contract/index.js";
export { Client as JuryClient } from "./generated/jury-registry/index.js";
export { Client as IdentityClient } from "./generated/identity-registry/index.js";
=======
// Re-export from local bindings (copied from generated packages)
// These are generated by: npx @stellar/stellar-sdk generate
// Kept here for reference; the web app imports from src/lib/bindings/

export const PLATFORM_CONTRACT_ID = "CB3X25J5HTYZJT5YETSU7EJDL237L7DFBKPQNC3ZMKVNDR7RTZDD2BEV";
export const ESCROW_CONTRACT_ID = "CC5YIIBETTIJ2DTYK5H5V4MIM574QH6KL3INPDTSFA5O43LRUVN6H3C3";
export const RPC_URL = "https://soroban-testnet.stellar.org";
export const NETWORK_PASSPHRASE = "Test SDF Network ; September 2015";
>>>>>>> b2133f6 (Initial frontend setup)
